import type { Metadata } from "next";
import { Lexend_Deca } from 'next/font/google';
import "./globals.css";

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // pesos que necesites
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: "Dashboard Sensores App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.className}`}>
        {children}
      </body>
    </html>
  );
}
